export interface NameMatch {
  name: string;
  offset: number;
  length: number;
  confidence: number;
}

// First names: German, English, Turkish, Arabic, Polish, Italian, Indian.
// Covers ~90% of encounters in international enterprise codebases.
const FIRST_NAMES = new Set([
  // Male
  'Alexander',
  'Andreas',
  'Anton',
  'Artur',
  'Axel',
  'Benjamin',
  'Bernd',
  'Bernhard',
  'Boris',
  'Bruno',
  'Carl',
  'Carlo',
  'Carsten',
  'Christian',
  'Christoph',
  'Christopher',
  'Claus',
  'Daniel',
  'David',
  'Dennis',
  'Dieter',
  'Dirk',
  'Dominik',
  'Eduard',
  'Elias',
  'Emil',
  'Erik',
  'Ernst',
  'Erwin',
  'Fabian',
  'Felix',
  'Ferdinand',
  'Finn',
  'Florian',
  'Frank',
  'Franz',
  'Friedrich',
  'Fritz',
  'Georg',
  'Gerhard',
  'Gregor',
  'Günter',
  'Günther',
  'Gustav',
  'Hans',
  'Harald',
  'Hartmut',
  'Heinrich',
  'Helmut',
  'Hendrik',
  'Henrik',
  'Herbert',
  'Hermann',
  'Holger',
  'Horst',
  'Hugo',
  'Ingo',
  'Ivan',
  'Jakob',
  'Jan',
  'Jens',
  'Joachim',
  'Jochen',
  'Johann',
  'Johannes',
  'Jonas',
  'Jonathan',
  'Josef',
  'Julian',
  'Julius',
  'Jürgen',
  'Kai',
  'Karl',
  'Karsten',
  'Klaus',
  'Konrad',
  'Kurt',
  'Lars',
  'Leo',
  'Leon',
  'Leonard',
  'Leonhard',
  'Lorenz',
  'Lothar',
  'Louis',
  'Luca',
  'Ludwig',
  'Luis',
  'Lukas',
  'Lutz',
  'Manfred',
  'Manuel',
  'Marc',
  'Marcel',
  'Marco',
  'Marcus',
  'Mario',
  'Markus',
  'Martin',
  'Mathias',
  'Matthias',
  'Max',
  'Maximilian',
  'Michael',
  'Moritz',
  'Nico',
  'Nicolas',
  'Niklas',
  'Nikolaus',
  'Nils',
  'Noah',
  'Norbert',
  'Oliver',
  'Oscar',
  'Oskar',
  'Otto',
  'Patrick',
  'Paul',
  'Peter',
  'Philipp',
  'Rafael',
  'Rainer',
  'Ralf',
  'Reinhard',
  'Reinhold',
  'René',
  'Richard',
  'Robert',
  'Robin',
  'Roland',
  'Rolf',
  'Roman',
  'Rudolf',
  'Rüdiger',
  'Samuel',
  'Sascha',
  'Sebastian',
  'Siegfried',
  'Simon',
  'Stefan',
  'Steffen',
  'Stephan',
  'Sven',
  'Theodor',
  'Thomas',
  'Thorsten',
  'Til',
  'Till',
  'Tilo',
  'Tim',
  'Timo',
  'Tobias',
  'Torsten',
  'Udo',
  'Ulrich',
  'Uwe',
  'Valentin',
  'Viktor',
  'Volker',
  'Walter',
  'Werner',
  'Wilhelm',
  'Willi',
  'Wolfgang',

  // Female
  'Adelheid',
  'Agnes',
  'Alexandra',
  'Alina',
  'Amelie',
  'Andrea',
  'Angelika',
  'Anika',
  'Anja',
  'Anna',
  'Annalena',
  'Anne',
  'Anneliese',
  'Annette',
  'Antje',
  'Astrid',
  'Barbara',
  'Beate',
  'Bianca',
  'Birgit',
  'Brigitte',
  'Britta',
  'Carla',
  'Carmen',
  'Caroline',
  'Charlotte',
  'Christa',
  'Christina',
  'Christine',
  'Clara',
  'Claudia',
  'Cornelia',
  'Dagmar',
  'Dana',
  'Daniela',
  'Diana',
  'Doris',
  'Dorothea',
  'Edith',
  'Elena',
  'Elfriede',
  'Elisabeth',
  'Elke',
  'Ella',
  'Emilia',
  'Emma',
  'Erika',
  'Erna',
  'Eva',
  'Franziska',
  'Freya',
  'Frieda',
  'Friederike',
  'Gabriele',
  'Gerda',
  'Gertrud',
  'Gisela',
  'Greta',
  'Gudrun',
  'Hanna',
  'Hannah',
  'Hannelore',
  'Heide',
  'Heidi',
  'Heike',
  'Helene',
  'Helga',
  'Hildegard',
  'Ilona',
  'Ilse',
  'Ina',
  'Ines',
  'Ingrid',
  'Irene',
  'Iris',
  'Isabel',
  'Isolde',
  'Jana',
  'Janina',
  'Jasmin',
  'Jennifer',
  'Jessica',
  'Johanna',
  'Julia',
  'Juliane',
  'Karin',
  'Karla',
  'Karolina',
  'Katarina',
  'Katharina',
  'Kathrin',
  'Katja',
  'Kerstin',
  'Klara',
  'Kristin',
  'Laura',
  'Lena',
  'Leonie',
  'Liane',
  'Lina',
  'Linda',
  'Lisa',
  'Lotte',
  'Luisa',
  'Luise',
  'Madeleine',
  'Magdalena',
  'Manuela',
  'Margarete',
  'Maria',
  'Marie',
  'Marina',
  'Marion',
  'Marlene',
  'Martha',
  'Martina',
  'Mathilde',
  'Meike',
  'Melanie',
  'Michaela',
  'Miriam',
  'Monika',
  'Nadine',
  'Natascha',
  'Nicole',
  'Nina',
  'Nora',
  'Olga',
  'Patricia',
  'Pauline',
  'Petra',
  'Pia',
  'Rebecca',
  'Regina',
  'Renate',
  'Rita',
  'Rosa',
  'Rosemarie',
  'Ruth',
  'Sabine',
  'Sandra',
  'Sara',
  'Sarah',
  'Sigrid',
  'Silke',
  'Simone',
  'Sofia',
  'Sonja',
  'Sophia',
  'Sophie',
  'Stefanie',
  'Stephanie',
  'Susanne',
  'Sylvia',
  'Tanja',
  'Teresa',
  'Theresa',
  'Tina',
  'Ulrike',
  'Ursula',
  'Ute',
  'Vanessa',
  'Vera',
  'Veronika',
  'Victoria',
  'Waltraud',
  'Wiebke',

  // Common English first names (overlap with international teams)
  'Adam',
  'Alice',
  'Amanda',
  'Amy',
  'Andrew',
  'Angela',
  'Anthony',
  'Ashley',
  'Brian',
  'Bruce',
  'Catherine',
  'Charles',
  'Chris',
  'Colin',
  'Craig',
  'Deborah',
  'Donald',
  'Dorothy',
  'Douglas',
  'Edward',
  'Elizabeth',
  'Emily',
  'Eric',
  'Ethan',
  'George',
  'Grace',
  'Gregory',
  'Harold',
  'Harry',
  'Helen',
  'Henry',
  'Jack',
  'Jacob',
  'James',
  'Jane',
  'Jason',
  'Jeffrey',
  'Jennifer',
  'Jeremy',
  'Jessica',
  'Joan',
  'Joe',
  'John',
  'Joseph',
  'Joshua',
  'Justin',
  'Karen',
  'Katherine',
  'Keith',
  'Kelly',
  'Kenneth',
  'Kevin',
  'Kyle',
  'Lauren',
  'Lawrence',
  'Lily',
  'Logan',
  'Margaret',
  'Mark',
  'Mary',
  'Mason',
  'Matthew',
  'Megan',
  'Melissa',
  'Michelle',
  'Nancy',
  'Nathan',
  'Nicholas',
  'Noah',
  'Olivia',
  'Oscar',
  'Pamela',
  'Patricia',
  'Philip',
  'Rachel',
  'Raymond',
  'Rebecca',
  'Richard',
  'Ronald',
  'Russell',
  'Ryan',
  'Samantha',
  'Sandra',
  'Scott',
  'Sharon',
  'Sophia',
  'Stephen',
  'Steven',
  'Susan',
  'Taylor',
  'Timothy',
  'Tyler',
  'Victoria',
  'Virginia',
  'William',

  // Turkish
  'Ahmet',
  'Ali',
  'Ayşe',
  'Burak',
  'Cem',
  'Deniz',
  'Elif',
  'Emine',
  'Emre',
  'Fatma',
  'Gül',
  'Hakan',
  'Hasan',
  'Hüseyin',
  'Kemal',
  'Leyla',
  'Mehmet',
  'Murat',
  'Mustafa',
  'Neslihan',
  'Nur',
  'Oğuz',
  'Ömer',
  'Özlem',
  'Recep',
  'Selim',
  'Serkan',
  'Sibel',
  'Sümeyye',
  'Tuncay',
  'Ümit',
  'Yasemin',
  'Yusuf',
  'Zeynep',

  // Arabic
  'Abdul',
  'Abdullah',
  'Ahmad',
  'Ahmed',
  'Aisha',
  'Amina',
  'Amir',
  'Farid',
  'Fatima',
  'Habib',
  'Hamid',
  'Hassan',
  'Hussain',
  'Ibrahim',
  'Jamal',
  'Karim',
  'Khalid',
  'Layla',
  'Mahmoud',
  'Mariam',
  'Mohammed',
  'Mostafa',
  'Nadia',
  'Nasser',
  'Omar',
  'Rashid',
  'Samir',
  'Tariq',
  'Yasmin',
  'Youssef',
  'Zainab',

  // Polish
  'Agnieszka',
  'Andrzej',
  'Beata',
  'Dariusz',
  'Dorota',
  'Ewa',
  'Grzegorz',
  'Iwona',
  'Jakub',
  'Janusz',
  'Joanna',
  'Katarzyna',
  'Krzysztof',
  'Łukasz',
  'Małgorzata',
  'Marcin',
  'Marek',
  'Mariusz',
  'Mateusz',
  'Paweł',
  'Piotr',
  'Rafał',
  'Stanisław',
  'Tomasz',
  'Wojciech',
  'Zbigniew',

  // Italian
  'Alessandro',
  'Alessia',
  'Chiara',
  'Davide',
  'Federica',
  'Francesca',
  'Giacomo',
  'Giorgio',
  'Giovanni',
  'Giuseppe',
  'Giulia',
  'Lucia',
  'Luigi',
  'Matteo',
  'Paola',
  'Paolo',
  'Roberto',
  'Salvatore',
  'Simone',
  'Stefano',
  'Valentina',

  // Indian
  'Aditya',
  'Amit',
  'Anil',
  'Anita',
  'Arjun',
  'Deepak',
  'Divya',
  'Ganesh',
  'Hari',
  'Kavita',
  'Krishna',
  'Lakshmi',
  'Manoj',
  'Neha',
  'Priya',
  'Rahul',
  'Rajesh',
  'Ravi',
  'Rohit',
  'Sachin',
  'Sandeep',
  'Sanjay',
  'Shivani',
  'Sunil',
  'Sunita',
  'Suresh',
  'Vijay',
  'Vikram',
  'Vinod',
]);

// Last names: German, English, Turkish, Arabic, Polish, Italian, Indian.
const LAST_NAMES = new Set([
  'Abel',
  'Ackermann',
  'Adam',
  'Adler',
  'Albrecht',
  'Alt',
  'Altmann',
  'Ammann',
  'Bach',
  'Bachmann',
  'Bader',
  'Bahr',
  'Bartels',
  'Barth',
  'Bartsch',
  'Basler',
  'Bauer',
  'Baumann',
  'Baumgartner',
  'Beck',
  'Becker',
  'Beer',
  'Behrendt',
  'Behrens',
  'Beier',
  'Berger',
  'Bergmann',
  'Berndt',
  'Bernhardt',
  'Bertram',
  'Best',
  'Beyer',
  'Bischoff',
  'Bittner',
  'Blank',
  'Blum',
  'Bock',
  'Böhm',
  'Böhme',
  'Böttcher',
  'Brandt',
  'Braun',
  'Brendel',
  'Brinkmann',
  'Brock',
  'Brückner',
  'Brüggemann',
  'Brunner',
  'Büchner',
  'Bühler',
  'Burger',
  'Burkhardt',
  'Busch',
  'Busse',
  'Conrad',
  'Decker',
  'Diehl',
  'Dietrich',
  'Dittrich',
  'Döring',
  'Dorn',
  'Ebert',
  'Eckert',
  'Eder',
  'Ehlert',
  'Eichhorn',
  'Engel',
  'Engelhardt',
  'Erdmann',
  'Ernst',
  'Falk',
  'Fehr',
  'Feldmann',
  'Fiedler',
  'Fischer',
  'Fleischer',
  'Förster',
  'Frank',
  'Franke',
  'Franz',
  'Freund',
  'Frey',
  'Friedrich',
  'Fritsch',
  'Fritz',
  'Fuchs',
  'Funke',
  'Gärtner',
  'Geiger',
  'Geißler',
  'Gerber',
  'Gerlach',
  'Giese',
  'Glaser',
  'Götze',
  'Graf',
  'Greiner',
  'Grimm',
  'Groß',
  'Große',
  'Gruber',
  'Grün',
  'Günther',
  'Haas',
  'Haase',
  'Hagen',
  'Hahn',
  'Hammer',
  'Hanke',
  'Hansen',
  'Hartmann',
  'Hartung',
  'Haupt',
  'Hauser',
  'Heck',
  'Hein',
  'Heinrich',
  'Heinz',
  'Held',
  'Heller',
  'Henke',
  'Henkel',
  'Hennig',
  'Hentschel',
  'Herbert',
  'Hermann',
  'Herold',
  'Herrmann',
  'Herzog',
  'Heß',
  'Hesse',
  'Hildebrandt',
  'Hinz',
  'Hirsch',
  'Hoffmann',
  'Hofmann',
  'Hohmann',
  'Horn',
  'Huber',
  'Hummel',
  'Jacob',
  'Jäger',
  'Jahn',
  'Jakob',
  'Janssen',
  'John',
  'Jordan',
  'Jost',
  'Jung',
  'Junge',
  'Jungblut',
  'Junker',
  'Jürgens',
  'Kaiser',
  'Kappel',
  'Karl',
  'Kaufmann',
  'Keil',
  'Keller',
  'Kellner',
  'Kern',
  'Kessler',
  'Kirchner',
  'Klatt',
  'Klein',
  'Klemm',
  'Klose',
  'Kluge',
  'Knoll',
  'Koch',
  'König',
  'Körner',
  'Kraft',
  'Kramer',
  'Kraus',
  'Krause',
  'Kremer',
  'Kretschmer',
  'Krieger',
  'Kröger',
  'Kroll',
  'Krüger',
  'Kühn',
  'Kuhn',
  'Kunz',
  'Kunze',
  'Kurz',
  'Lang',
  'Lange',
  'Langer',
  'Lauer',
  'Lehmann',
  'Lehner',
  'Lenz',
  'Lindemann',
  'Lindner',
  'Link',
  'Lohmann',
  'Lorenz',
  'Ludwig',
  'Lüdtke',
  'Maier',
  'Mann',
  'Martin',
  'Marx',
  'Maurer',
  'May',
  'Mayer',
  'Meier',
  'Meister',
  'Menzel',
  'Merkel',
  'Mertens',
  'Merz',
  'Metz',
  'Meyer',
  'Michel',
  'Möller',
  'Mohr',
  'Moritz',
  'Müller',
  'Münch',
  'Nagel',
  'Naumann',
  'Neubert',
  'Neuhaus',
  'Neumann',
  'Niemann',
  'Noack',
  'Nolte',
  'Nowak',
  'Oertel',
  'Orth',
  'Otto',
  'Paul',
  'Peters',
  'Petersen',
  'Pfeifer',
  'Pfeiffer',
  'Pflüger',
  'Pohl',
  'Popp',
  'Preuß',
  'Raab',
  'Rapp',
  'Rau',
  'Rauch',
  'Reimann',
  'Reinhardt',
  'Reiter',
  'Renner',
  'Richter',
  'Riedel',
  'Rieger',
  'Ring',
  'Ritter',
  'Röder',
  'Roth',
  'Rudolph',
  'Ruf',
  'Sander',
  'Sauer',
  'Schäfer',
  'Schaller',
  'Scharf',
  'Scheffler',
  'Schenk',
  'Scherer',
  'Schiller',
  'Schilling',
  'Schlegel',
  'Schlüter',
  'Schmidt',
  'Schmidtke',
  'Schmitt',
  'Schmitz',
  'Schneider',
  'Scholz',
  'Schön',
  'Schreiber',
  'Schröder',
  'Schubert',
  'Schulte',
  'Schultz',
  'Schulz',
  'Schulze',
  'Schumacher',
  'Schuster',
  'Schwab',
  'Schwartz',
  'Schwarz',
  'Schweizer',
  'Seidel',
  'Seifert',
  'Siebert',
  'Siegmund',
  'Simon',
  'Singer',
  'Sommer',
  'Sonntag',
  'Stadler',
  'Stark',
  'Steffens',
  'Steiner',
  'Steinmann',
  'Stephan',
  'Stock',
  'Stoll',
  'Straub',
  'Strauss',
  'Strauß',
  'Thiel',
  'Thieme',
  'Thomas',
  'Timm',
  'Ullrich',
  'Ulrich',
  'Unger',
  'Vogt',
  'Voigt',
  'Volk',
  'Volkmann',
  'Voss',
  'Voß',
  'Wagner',
  'Walther',
  'Weber',
  'Wegner',
  'Weiß',
  'Weller',
  'Wendler',
  'Wendt',
  'Wenzel',
  'Werner',
  'Westphal',
  'Wiedemann',
  'Wiegand',
  'Wiese',
  'Wild',
  'Wilhelm',
  'Winkler',
  'Winter',
  'Wirth',
  'Witt',
  'Witte',
  'Wolf',
  'Wolff',
  'Wolter',
  'Wulf',
  'Wunderlich',
  'Zander',
  'Zeller',
  'Ziegler',
  'Zimmermann',
  'Zink',

  // Common English last names
  'Anderson',
  'Bailey',
  'Baker',
  'Barnes',
  'Bennett',
  'Brooks',
  'Brown',
  'Butler',
  'Campbell',
  'Carter',
  'Clark',
  'Clarke',
  'Collins',
  'Cook',
  'Cooper',
  'Cox',
  'Crawford',
  'Davis',
  'Dixon',
  'Edwards',
  'Ellis',
  'Evans',
  'Fisher',
  'Foster',
  'Fox',
  'Garcia',
  'Gibson',
  'Gordon',
  'Graham',
  'Grant',
  'Green',
  'Griffin',
  'Hall',
  'Hamilton',
  'Harris',
  'Harrison',
  'Harvey',
  'Henderson',
  'Hill',
  'Holmes',
  'Howard',
  'Hughes',
  'Hunt',
  'Hunter',
  'Jackson',
  'Jenkins',
  'Johnson',
  'Jones',
  'Kelly',
  'Kennedy',
  'King',
  'Knight',
  'Lawrence',
  'Lewis',
  'Lloyd',
  'Marshall',
  'Mason',
  'Miller',
  'Mills',
  'Mitchell',
  'Moore',
  'Morgan',
  'Morris',
  'Murphy',
  'Murray',
  'Nelson',
  'Newman',
  'Oliver',
  'Owen',
  'Palmer',
  'Parker',
  'Patterson',
  'Phillips',
  'Porter',
  'Powell',
  'Price',
  'Reed',
  'Reid',
  'Reynolds',
  'Richardson',
  'Riley',
  'Roberts',
  'Robertson',
  'Robinson',
  'Rogers',
  'Ross',
  'Russell',
  'Sanders',
  'Scott',
  'Shaw',
  'Simpson',
  'Smith',
  'Spencer',
  'Stevens',
  'Stewart',
  'Stone',
  'Sullivan',
  'Taylor',
  'Thompson',
  'Tucker',
  'Turner',
  'Walker',
  'Wallace',
  'Ward',
  'Warren',
  'Watson',
  'Webb',
  'Wells',
  'West',
  'White',
  'Williams',
  'Wilson',
  'Wood',
  'Wright',
  'Young',

  // Turkish
  'Aksoy',
  'Arslan',
  'Aydın',
  'Çelik',
  'Demir',
  'Doğan',
  'Erdoğan',
  'Güneş',
  'Kara',
  'Kaya',
  'Koç',
  'Korkmaz',
  'Öz',
  'Özdemir',
  'Özkan',
  'Öztürk',
  'Şahin',
  'Şen',
  'Toprak',
  'Türk',
  'Yıldırım',
  'Yıldız',
  'Yılmaz',

  // Arabic
  'Al-Ahmad',
  'Al-Ali',
  'Al-Hassan',
  'Al-Hussein',
  'Al-Rahman',
  'Al-Rashid',
  'El-Sayed',
  'Habib',
  'Ibrahim',
  'Mansour',
  'Nasser',
  'Said',
  'Saleh',

  // Polish
  'Baran',
  'Dąbrowski',
  'Grabowski',
  'Jabłoński',
  'Jankowski',
  'Kamiński',
  'Kowalczyk',
  'Kowalski',
  'Krawczyk',
  'Lewandowski',
  'Mazur',
  'Michalski',
  'Olszewski',
  'Pawlak',
  'Piotrowski',
  'Szymański',
  'Wiśniewski',
  'Wójcik',
  'Wojciechowski',
  'Woźniak',
  'Zieliński',

  // Italian
  'Bianchi',
  'Colombo',
  'Conti',
  'Costa',
  'DeLuca',
  'Esposito',
  'Ferrari',
  'Ferro',
  'Gallo',
  'Greco',
  'Leone',
  'Lombardi',
  'Mancini',
  'Marino',
  'Moretti',
  'Ricci',
  'Romano',
  'Rossi',
  'Russo',
  'Santoro',
  'Vitale',

  // Indian
  'Agarwal',
  'Banerjee',
  'Bhat',
  'Chakraborty',
  'Chatterjee',
  'Das',
  'Desai',
  'Ghosh',
  'Gupta',
  'Iyer',
  'Jain',
  'Joshi',
  'Kapoor',
  'Khan',
  'Kumar',
  'Malhotra',
  'Mehta',
  'Mishra',
  'Mukherjee',
  'Nair',
  'Patel',
  'Rao',
  'Reddy',
  'Shah',
  'Sharma',
  'Singh',
  'Srivastava',
  'Verma',
]);

// Words that look like names but are actually programming terms, brands, or common nouns.
// Overlaps with the openredaction-bridge blocklist but specifically for dictionary matching.
const BLOCKLIST = new Set([
  // Programming / tech that overlap with name sets
  'Adam',
  'Grace',
  'Ruby',
  'Iris',
  'Dawn',
  'Amber',
  'Jade',
  'Ivy',
  'Heath',
  'Grant',
  'Chase',
  'Hunter',
  'Mason',
  'Cooper',
  'Carter',
  'Parker',
  'Tyler',
  'Logan',
  'Taylor',
  'Reed',
  'Stone',
  'Fox',
  'Young',
  'King',
  'Knight',
  // Common in code context
  'Node',
  'Spring',
  'Express',
  'React',
  'Vue',
  'Angular',
  'Docker',
  'Kafka',
  'Oracle',
  'Lambda',
  'Delta',
  'Alpha',
  'Beta',
  'Gamma',
  'Sigma',
  'Omega',
  'Buffer',
  'Stream',
  'String',
  'Array',
  'Object',
  'Class',
  'Module',
  'Event',
  'Error',
  'Promise',
  'Proxy',
  'Handler',
  'Builder',
  'Factory',
  'Service',
  'Client',
  'Server',
  'Worker',
  'Manager',
  'Controller',
  'Provider',
  'Consumer',
  'Adapter',
  'Router',
  'Logger',
  'Mapper',
  'Parser',
  'Scanner',
  'Reader',
  'Writer',
  'Loader',
  'Finder',
  'Helper',
  'Wrapper',
  'Runner',
  'Driver',
  'Sender',
  'Receiver',
  'Plugin',
  'Config',
  'Context',
  'Resolver',
  'Validator',
  'Converter',
  'Iterator',
  'Generator',
  'Observer',
  'Listener',
  'Monitor',
  'Tracker',
  'Scheduler',
  'Dispatcher',
  'Interceptor',
  'Inspector',
  // Git / version control
  'Merge',
  'Branch',
  'Remote',
  'Origin',
  'Master',
  'Release',
  // Misc
  'Test',
  'Mock',
  'Stub',
  'Fake',
  'Dummy',
  'Default',
  'Custom',
  'Abstract',
  'Base',
  'Root',
  'Main',
  'Core',
  'Utils',
  'Util',
  'True',
  'False',
  'Null',
  'Void',
  'None',
  'North',
  'South',
  'East',
  'West',
  'Red',
  'Blue',
  'Black',
  'White',
  'Green',
  'Brown',
  'Grey',
  'Gray',
  'Jan',
  'Mar',
  'May',
  'Jun',
  'Jul',
  'Aug',
  // German titles / salutations (used as prefix triggers, not as names themselves)
  'Herr',
  'Frau',
  'Herrn',
  'Doktor',
  // German words that start uppercase (Das = also Indian surname, but too common as article)
  'Das',
  'Typ',
  'Art',
  'Feld',
  'Wert',
  'Klasse',
  'Schritt',
  'Teil',
  'Punkt',
  'Beginn',
  'Ende',
  'Start',
  'Status',
  'Phase',
  'Ebene',
  'Stufe',
  'Fehler',
  'Erfolg',
  'Hinweis',
  'Frage',
  'Antwort',
  'Lösung',
  'Aufgabe',
  'Name',
  'Datum',
  'Zeit',
  'Dauer',
  'Stelle',
  'Bereich',
  'Tabelle',
  'Spalte',
  'Zeile',
  'Nummer',
  'Betrag',
  'Adresse',
  'Standort',
  'Ergebnis',
  'Beispiel',
  'Muster',
  'Vorlage',
  'Grundlage',
]);

// Contextual prefixes that strongly indicate a following word is a person name.
const NAME_PREFIXES = [
  /\b(?:Herr|Frau|Hr\.|Fr\.)\s+/g,
  /\b(?:Dr\.|Prof\.|Ing\.)\s+/g,
  /\b(?:Author|Autor|Reviewer|Maintainer|Erstellt von|Geprüft von|Bearbeiter|Ansprechpartner|Kontakt|Verantwortlich):\s*/gi,
  /\b(?:Signed-off-by|Reported-by|Reviewed-by|Co-authored-by):\s*/gi,
  /\b(?:von|by|from)\s+(?=[A-ZÄÖÜŁŞİĞÇĆŃŹŻ])/g,
  /(?:@author|@since|@reviewer)\s+/gi,
];

// Matches a capitalized word (German umlauts, Turkish ş/ı/ğ/ç, Polish ł/ą/ę/ź/ć/ń/ż/ó).
const CAP_WORD = /[A-ZÄÖÜŁŞİĞÇĆŃŹŻ][a-zäöüßşığçłąęźćńżó]+/;
const CAP_WORD_RE = new RegExp(CAP_WORD.source, 'g');

// Full name: "FirstName LastName" or "FirstName Al-LastName" with optional middle parts
const FULL_NAME_RE = new RegExp(
  `(${CAP_WORD.source})(?:\\s+${CAP_WORD.source})*\\s+(?:(?:Al|El)-)?(?:${CAP_WORD.source})`,
  'g',
);

function isCapitalized(word: string): boolean {
  return /^[A-ZÄÖÜŁŞĞÇĆŃŹŻİ]/.test(word);
}

function looksLikeCamelCase(text: string, offset: number): boolean {
  if (offset === 0) return false;
  const prev = text[offset - 1];
  return /[a-zäöüßşığçłąęźćńżó]/.test(prev);
}

function isInsideCodeBlock(text: string, offset: number): boolean {
  // Check if surrounded by backticks or inside a code-like structure
  const before = text.slice(Math.max(0, offset - 50), offset);
  const after = text.slice(offset, Math.min(text.length, offset + 80));

  // Inside backtick block
  const btBefore = (before.match(/`/g) || []).length;
  if (btBefore % 2 === 1) return true;

  // Looks like a class/function definition
  if (/(?:class|interface|enum|function|const|let|var|type|import|export)\s+$/.test(before))
    return true;

  // Is followed by a dot, parenthesis, or angle bracket (method call / generic)
  if (/^[.(/<]/.test(after.slice(text.slice(offset).match(CAP_WORD_RE)?.[0]?.length ?? 0)))
    return true;

  return false;
}

function isBlocklisted(word: string): boolean {
  return BLOCKLIST.has(word);
}

function isFirstName(word: string): boolean {
  return FIRST_NAMES.has(word) && !isBlocklisted(word);
}

function isLastName(word: string): boolean {
  return LAST_NAMES.has(word) && !isBlocklisted(word);
}

function hasLastNameSuffix(word: string): boolean {
  const suffixes = [
    'mann',
    'stein',
    'berg',
    'burg',
    'ner',
    'ler',
    'ger',
    'meyer',
    'meier',
    'maier',
    'müller',
    'mayer',
    'bauer',
    'huber',
    'feld',
    'dorf',
    'hof',
    'bach',
    'brück',
    'thal',
    'wald',
    'witz',
    'rath',
    'hagen',
    'kamp',
  ];
  const lower = word.toLowerCase();
  if (lower.length < 4) return false;
  return suffixes.some((s) => lower.endsWith(s) && lower.length > s.length + 1);
}

export function detectNames(text: string): NameMatch[] {
  const hits: NameMatch[] = [];
  const coveredRanges: Array<[number, number]> = [];

  function isAlreadyCovered(offset: number, length: number): boolean {
    return coveredRanges.some(([s, e]) => offset >= s && offset + length <= e);
  }

  function markCovered(offset: number, length: number): void {
    coveredRanges.push([offset, offset + length]);
  }

  // Pass 1: context-triggered names (high confidence).
  // Look for names preceded by explicit markers like "Herr", "Dr.", "Author:", etc.
  for (const prefixRe of NAME_PREFIXES) {
    const re = new RegExp(prefixRe.source, prefixRe.flags);
    let pm: RegExpExecArray | null;

    while ((pm = re.exec(text)) !== null) {
      const afterPrefix = text.slice(pm.index + pm[0].length);
      // Also match Arabic-style compound last names like "Al-Rahman"
      const AL_PART = `(?:(?:Al|El)-)?${CAP_WORD.source}`;
      const nameMatch = afterPrefix.match(
        new RegExp(`^(${CAP_WORD.source}(?:\\s+${AL_PART}){0,3})`),
      );
      if (!nameMatch) continue;

      const fullName = nameMatch[1];
      const words = fullName.split(/\s+/);

      // At least one word must not be blocklisted
      if (words.every((w) => isBlocklisted(w))) continue;

      // Reject if it looks like code
      const nameOffset = pm.index + pm[0].length;
      if (isInsideCodeBlock(text, nameOffset)) continue;

      const confidence = 0.9;
      hits.push({
        name: fullName,
        offset: nameOffset,
        length: fullName.length,
        confidence,
      });
      markCovered(nameOffset, fullName.length);
    }
  }

  // Pass 2: dictionary-matched full names (medium-high confidence).
  // Match "Firstname Lastname" pairs where both parts are in dictionaries.
  const fullRe = new RegExp(FULL_NAME_RE.source, FULL_NAME_RE.flags);
  let fm: RegExpExecArray | null;

  while ((fm = fullRe.exec(text)) !== null) {
    const fullMatch = fm[0];
    const offset = fm.index;

    if (isAlreadyCovered(offset, fullMatch.length)) continue;
    if (looksLikeCamelCase(text, offset)) continue;
    if (isInsideCodeBlock(text, offset)) continue;

    const words = fullMatch.split(/\s+/);
    const first = words[0];
    const last = words[words.length - 1];

    // Skip if all words are blocklisted
    if (words.every((w) => isBlocklisted(w))) continue;

    // Both first and last must be recognized
    const firstOk = isFirstName(first);
    const lastOk = isLastName(last) || hasLastNameSuffix(last);

    if (!firstOk && !lastOk) continue;

    let confidence: number;
    if (firstOk && lastOk) {
      confidence = 0.85;
    } else if (firstOk && isCapitalized(last) && !isBlocklisted(last)) {
      // Known first name + unknown but capitalized last name
      confidence = 0.7;
    } else if (lastOk && isCapitalized(first) && !isBlocklisted(first)) {
      // Unknown first name + known last name
      confidence = 0.7;
    } else {
      continue;
    }

    // Extra check: reject if the "name" is at the start of a sentence and
    // followed by a verb-like lowercase word - might just be a regular German sentence.
    // But only if neither word is in the dictionary at all.
    if (!firstOk && !lastOk) continue;

    hits.push({ name: fullMatch, offset, length: fullMatch.length, confidence });
    markCovered(offset, fullMatch.length);

    // Reset regex index to right after first word to catch overlapping patterns.
    // +1 skips the whitespace separator between first name and last name so the
    // next match attempt starts at a real token boundary.
    fullRe.lastIndex = offset + first.length + 1;
  }

  // Deduplicate and sort by offset
  hits.sort((a, b) => a.offset - b.offset);
  return hits;
}
