import { OpenRedaction } from 'openredaction';
import type { PatternMatch } from './utils.js';

type PresetName = 'gdpr' | 'hipaa' | 'ccpa' | 'healthcare' | 'finance' | 'pci-dss' | 'soc2';
type CompliancePreset = PresetName | undefined;

interface BridgeOptions {
  preset?: string;
}

const FALSE_POSITIVE_BLOCKLIST = new Set([
  // SQL keywords
  'select',
  'where',
  'from',
  'join',
  'delete',
  'update',
  'insert',
  'and',
  'or',
  'not',
  'group',
  'order',
  'having',
  'union',
  'limit',
  'offset',
  'create',
  'alter',
  'drop',
  'table',
  'index',
  'view',
  'trigger',
  'grant',
  'revoke',
  'set',
  'values',
  'into',
  'between',
  'exists',
  'distinct',
  'count',
  'sum',
  'avg',
  'min',
  'max',
  'case',
  'when',
  'then',
  'else',
  'end',
  'commit',
  'rollback',
  'transaction',
  'constraint',
  'primary',
  'foreign',
  'references',
  'cascade',
  'procedure',
  'function',
  'schema',
  'database',
  'execute',
  'begin',
  'declare',
  'cursor',
  'fetch',
  'open',
  'close',
  // Programming languages / tech
  'java',
  'php',
  'python',
  'javascript',
  'typescript',
  'kotlin',
  'scala',
  'ruby',
  'rust',
  'go',
  'kafka',
  'oracle',
  'apache',
  'docker',
  'kubernetes',
  'redis',
  'nginx',
  'maven',
  'gradle',
  'spring',
  'react',
  'angular',
  'vue',
  'express',
  'prisma',
  'vaadin',
  // Programming/framework terms
  'bean',
  'listener',
  'handler',
  'factory',
  'builder',
  'adapter',
  'converter',
  'override',
  'abstract',
  'interface',
  'implements',
  'extends',
  'static',
  'final',
  'private',
  'public',
  'protected',
  'return',
  'throw',
  'catch',
  'try',
  'optional',
  'stream',
  'mapping',
  'consumer',
  'producer',
  'supplier',
  'repository',
  'entity',
  'component',
  'module',
  'annotation',
  'configuration',
  'controller',
  'endpoint',
  'middleware',
  'interceptor',
  'resolver',
  'provider',
  'debezium',
  'camunda',
  'quarkus',
  'micronaut',
  'hibernate',
  'liquibase',
  // CI/CD and DevOps terms
  'push',
  'pull',
  'build',
  'deploy',
  'release',
  'container',
  'image',
  'volume',
  'network',
  'service',
  'pod',
  'node',
  'cluster',
  'helm',
  'chart',
  'pipeline',
  'stage',
  'job',
  'step',
  'runner',
  'agent',
  'worker',
  'task',
  'queue',
  'exchange',
  'download',
  'upload',
  'install',
  'package',
  'bundle',
  'artifact',
  'registry',
  'nexus',
  'npm',
  'pip',
  'cargo',
  'compose',
  // German common words that look like names
  'aggregation',
  'statistik',
  'berechnung',
  'manuell',
  'übersicht',
  'verwaltung',
  'konfiguration',
  'einstellung',
  'verarbeitung',
  'auswertung',
  'zusammenfassung',
  'beschreibung',
  'dokumentation',
  'implementierung',
  'integration',
  'migration',
  'validierung',
  'authentifizierung',
  'autorisierung',
  'benachrichtigung',
  'keine',
  'offene',
  'gute',
  'neue',
  'alle',
  'erste',
  'letzte',
  'aktuelle',
  'weitere',
  'erfahrung',
  'kompetenz',
  'passende',
  'wichtige',
  'verschiedene',
  'bestimmte',
  'ergebnis',
  'aufgabe',
  'lösung',
  'anforderung',
  'voraussetzung',
  'vorteil',
  'nachricht',
  'antwort',
  'frage',
  'hinweis',
  'warnung',
  'fehler',
  'erfolg',
  'abschluss',
  'beginn',
  'ende',
  'start',
  'status',
  'phase',
  'stufe',
  'ebene',
  'standort',
  'adresse',
  'nummer',
  'betrag',
  'datum',
  'zeit',
  'dauer',
  'name',
  'tabelle',
  'spalte',
  'zeile',
  'feld',
  'wert',
  'typ',
  'art',
  'form',
  'klasse',
  // SQL short keywords
  'on',
  'as',
  'is',
  'in',
  'to',
  'by',
  'if',
  'do',
  'go',
  'at',
  'no',
  'like',
  'with',
  'null',
  'left',
  'right',
  'inner',
  'outer',
  'cross',
  'full',
  'natural',
  // Common programming terms that get detected as names
  'none',
  'true',
  'false',
  'void',
  'type',
  'class',
  'enum',
  'string',
  'integer',
  'float',
  'double',
  'boolean',
  'object',
  'array',
  'dict',
  'dictionary',
  'tuple',
  'list',
  'vector',
  'map',
  'set',
  'row',
  'column',
  'field',
  'record',
  'entry',
  'item',
  'element',
  'exception',
  'error',
  'warning',
  'info',
  'debug',
  'trace',
  'hard',
  'soft',
  'lazy',
  'eager',
  'strict',
  'loose',
  'reject',
  'resolve',
  'pending',
  'fulfilled',
  'settled',
  'prefix',
  'suffix',
  'infix',
  'regex',
  'pattern',
  'match',
  'counter',
  'timer',
  'batch',
  'chunk',
  'page',
  'size',
  'geocoding',
  'scraping',
  'crawling',
  'parsing',
  'rendering',
  'scoring',
  'ranking',
  'sorting',
  'filtering',
  'grouping',
  'ordering',
  'break',
  'default',
  'switch',
  'loop',
  'while',
  'for',
  'each',
  'only',
  'just',
  'all',
  'any',
  'some',
  'every',
  'each',
  // Additional German words
  'mindest',
  'preis',
  'bereich',
  'teil',
  'punkt',
  'stelle',
  'schritt',
  'anfrage',
  'beratung',
  'überschrift',
  'inhalt',
  'eintrag',
  'übertrag',
  'beitrag',
  'auftrag',
  'vertrag',
  'zustand',
  'beispiel',
  'muster',
  'vorlage',
  'grundlage',
  // Game/media terms
  'level',
  'player',
  'score',
  'health',
  'damage',
  'armor',
  'attack',
  'defense',
  'sprite',
  'texture',
  'shader',
  'render',
  'viewport',
  'camera',
  'scene',
]);

const DISABLED_TYPES = new Set([
  'zip-code-us',
  'zip-code',
  'date',
  'instagram-username',
  'twitter-username',
  'tiktok-username',
  'facebook-username',
  'social-media-username',
]);

const detectors = new Map<string, OpenRedaction>();

function getDetector(preset?: string): OpenRedaction {
  const key = preset ?? '';
  let d = detectors.get(key);
  if (d) return d;
  d = new OpenRedaction({
    preset: preset as CompliancePreset,
    confidenceThreshold: 0.6,
    enableContextAnalysis: true,
    deterministic: true,
    includeNames: true,
    includeAddresses: true,
    includePhones: true,
    includeEmails: true,
  });
  detectors.set(key, d);
  return d;
}

// Concurrent callers with the same (preset, input) share a single in-flight
// detection promise. This prevents the earlier single-slot cache race where
// two interleaved calls could commit results bound to the wrong input.
const detectionCache = new Map<string, Promise<PatternMatch[]>>();
const DETECTION_CACHE_MAX = 128;

export async function detectWithOpenRedaction(
  input: string,
  opts?: BridgeOptions,
): Promise<PatternMatch[]> {
  const preset = opts?.preset ?? '';
  const key = `${preset}\u0000${input}`;

  const pending = detectionCache.get(key);
  if (pending) return pending;

  const run = (async () => {
    const detector = getDetector(opts?.preset);
    const result = await detector.detect(input);

    const results = result.detections
      .map((d) => ({
        type: normalizeType(d.type),
        match: d.value,
        offset: d.position[0],
        length: d.position[1] - d.position[0],
      }))
      .filter((r) => {
        if (DISABLED_TYPES.has(r.type)) return false;
        if (r.type === 'person-name' || r.type === 'name') {
          const trimmed = r.match.trim();
          const lower = trimmed.toLowerCase();
          if (FALSE_POSITIVE_BLOCKLIST.has(lower)) return false;
          const words = lower.split(/\s+/);
          if (words.some((w) => FALSE_POSITIVE_BLOCKLIST.has(w))) return false;
          if (/^[A-Z_]{2,}$/.test(trimmed)) return false;
        }
        return true;
      });

    return results;
  })();

  if (detectionCache.size >= DETECTION_CACHE_MAX) {
    // oldest-first eviction; Map iteration is insertion-ordered
    const oldest = detectionCache.keys().next().value;
    if (oldest !== undefined) detectionCache.delete(oldest);
  }
  detectionCache.set(key, run);
  return run;
}

const TYPE_MAP: Record<string, string> = {
  EMAIL: 'email',
  CREDIT_CARD: 'credit-card',
  IBAN: 'iban',
  PHONE_UK_MOBILE: 'phone',
  PHONE_UK: 'phone',
  PHONE_US: 'phone',
  PHONE_INTERNATIONAL: 'phone',
  PHONE_LINE_NUMBER: 'phone',
  IPV4: 'ipv4',
  IPV6: 'ipv6',
  MAC_ADDRESS: 'mac',
  AWS_ACCESS_KEY: 'aws-access-key',
  AWS_SECRET_KEY: 'aws-secret-key',
  GITHUB_TOKEN: 'github-token',
  NPM_TOKEN: 'npm-token',
  JWT_TOKEN: 'jwt',
  BEARER_TOKEN: 'bearer-token',
  PRIVATE_KEY: 'private-key',
  SSH_PRIVATE_KEY: 'private-key',
  DATABASE_CONNECTION: 'connection-string',
  GENERIC_SECRET: 'generic-secret',
  GENERIC_API_KEY: 'generic-secret',
  DATE_OF_BIRTH: 'date-of-birth',
  ADDRESS_STREET: 'address',
  ADDRESS_PO_BOX: 'address',
  POSTCODE_UK: 'address',
  GERMAN_TAX_ID: 'tax-id',
  NAME: 'person-name',
};

function normalizeType(orType: string): string {
  return TYPE_MAP[orType] ?? orType.toLowerCase().replace(/_/g, '-');
}
